%YAML:1.0

# Path to the images
dataset_dir: /home/feiyu/Desktop/slam/code/project/my2/dataset_images
# dataset_dir: /home/feiyu/Desktop/slam/code/project/my2/dataset_images_fr1
# Camera intrinsics
# -- fr1 dataset
# camera_info.fx: 517.3
# camera_info.fy: 516.5
# camera_info.cx: 325.1
# camera_info.cy: 249.7

# -- matlab dataset
camera_info.fx: 615
camera_info.fy: 615
camera_info.cx: 320
camera_info.cy: 240

# ------------------------ VO Parameters ------------------------ 

# Store the previous N frames and their features.
buffsize_of_prev_frames: 1

# Matching descriptos
feature_match_method_index: 2
  # method 1: the method in Dr. Xiang Gao's slambook:
  #           distance_threshold = max<float>(min_dis * match_ratio, 30.0);
  # method 2: the method in Lowe's 2004 paper:
  #           min dis / second min dis < 0.8
match_ratio: 2.0 # This is for method 1 used in Dr. Xiang Gao's slambook:

# remove wrong matches
GRID_SIZE: 16
MAX_PTS_IN_GRID: 2

# ORB settings 
number_of_keypoints_to_extract: 5000
max_number_of_keypoints: 1000
scale_factor: 1.2
level_pyramid: 4

# max_num_lost: 10
# min_inliers: 30
# keyframe_rotation: 0.1
# keyframe_translation: 0.1
# map_point_erase_ratio: 0.1